CREATE TABLE [dbo].[COMPRAS]
(
	[COMPRA_ID] INT NOT NULL PRIMARY KEY, 
    [NOMBRE_PROD] VARCHAR(50) NOT NULL, 
    [PROVEEDOR] VARCHAR(50) NOT NULL, 
    [TIPO_PROD] VARCHAR(50) NULL, 
    [PRECIO] NCHAR(10) NULL, 
    [VENTAS_ID] INT NOT NULL, 
    [PRODUCTO_ID] INT NOT NULL, 
    CONSTRAINT [FK_COMPRAS_VENTAS] FOREIGN KEY ([VENTAS_ID]) REFERENCES [VENTAS]([VENTAS_ID]), 
    CONSTRAINT [FK_COMPRAS_PRODUCTOS] FOREIGN KEY ([PRODUCTO_ID]) REFERENCES [PRODUCTOS]([PRODUCTO_ID])
)
